apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: forwarding
  namespace: openshift-logging # ClusterLogging Version 5.9.9
spec:
  inputs: 
    - application:
        namespaces:
          - core-application
      name: my-app-logs

  outputs:
    - elasticsearch:
        version: 8
      name: elasticsearch-external
      secret:
        name: elastic-secret
      type: elasticsearch
      url: 'http://elasticsearch-es-http.elastic-eck.svc:9200/'
      
  pipelines:
    - inputRefs:
        - my-app-logs
      name: application-logs
      outputRefs:
        - elasticsearch-external

  serviceAccountName: cluster-logging-operator 